stages:
  - tag

publish:
  stage: tag
  image: node:18
  services: []
  script:
    - echo "unsafe-perm = true" >> .npmrc
    - echo "@redturtle:registry=https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" >> .npmrc
    - echo "//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - yarn --immutable
    - npm publish
  only:
    - tags
